import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import PublicLayout from '@/Layouts/PublicLayout';
import PageHeader from '@/Components/PageHeader';
import Badge from '@/Components/Badge';
import { Clock3, Search } from 'lucide-react';

const date = (v) => v && new Date(v).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' });
const Picture = ({ item, className }) => <div className={`overflow-hidden bg-primary ${className}`}>{item.thumbnail ? <img src={`/storage/${item.thumbnail}`} alt={item.judul} className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105" /> : <div className="h-full w-full bg-gradient-to-br from-primary to-charcoal" />}</div>;

export default function BeritaIndex({ beritas, kategoris, pengumuman, filters }) {
    const [search, setSearch] = useState(filters.q || '');
    const data = beritas.data;
    const apply = (params) => router.get('/berita', { ...filters, ...params }, { preserveScroll: true, preserveState: true });
    return <PublicLayout>
        <Head title="Berita & Pengumuman" />
        <PageHeader title="Berita & Pengumuman" subtitle="Kabar terbaru, program, dan informasi resmi Desa Pematang Tatal" breadcrumbs={[{ label: 'Beranda', href: '/' }, { label: 'Berita' }]} />
        <main className="bg-background py-10"><div className="container-custom">
            <div className="mb-7 border-b-2 border-charcoal pb-4"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Pusat Informasi Desa</p><h1 className="mt-1 text-3xl font-extrabold text-charcoal" style={{ fontFamily: 'var(--font-heading)' }}>Kabar Terkini</h1></div><form onSubmit={(e) => { e.preventDefault(); apply({ q: search, page: 1 }); }} className="flex w-full gap-2 md:w-80"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="input-field !pl-9 !py-2" placeholder="Cari berita" /></div><button className="btn btn-primary py-2">Cari</button></form></div></div>
            <div className="mb-7 flex gap-2 overflow-x-auto pb-2"><button type="button" onClick={() => apply({ kategori: '', page: 1 })} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${!filters.kategori ? 'bg-primary text-white' : 'bg-white text-text-secondary'}`}>Semua</button>{kategoris.map((k) => <button key={k.id} type="button" onClick={() => apply({ kategori: k.slug, page: 1 })} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${filters.kategori === k.slug ? 'text-white' : 'bg-white text-text-secondary'}`} style={filters.kategori === k.slug ? { backgroundColor: k.warna } : {}}>{k.nama}</button>)}</div>
            {pengumuman.length > 0 && <div className="mb-8 rounded-md border border-accent-200 bg-accent-50 px-5 py-4"><span className="mr-5 text-xs font-extrabold uppercase tracking-wider text-accent-700">Pengumuman</span>{pengumuman.map((p) => <Link key={p.id} href={`/berita/${p.slug}`} className="mr-5 text-sm font-semibold text-charcoal hover:text-primary">{p.judul}</Link>)}</div>}
            {data.length > 0 && <section className="mb-10 grid grid-cols-1 gap-5 md:grid-cols-2"><Link href={`/berita/${data[0].slug}`} className="group relative min-h-[340px] overflow-hidden rounded-lg"><Picture item={data[0]} className="absolute inset-0" /><div className="absolute inset-0 bg-gradient-to-t from-charcoal via-charcoal/40 to-transparent" /><div className="relative flex min-h-[340px] flex-col justify-end p-7">{data[0].kategori && <Badge color={data[0].kategori.warna} className="mb-3 w-fit">{data[0].kategori.nama}</Badge>}<h2 className="text-2xl font-extrabold leading-tight text-white" style={{ fontFamily: 'var(--font-heading)' }}>{data[0].judul}</h2><p className="mt-3 flex items-center gap-1 text-xs text-white/75"><Clock3 size={13} />{date(data[0].published_at)}</p></div></Link><div className="divide-y divide-border-light rounded-lg bg-white px-5">{data.slice(1, 4).map((b) => <Link key={b.id} href={`/berita/${b.slug}`} className="group flex gap-4 py-5"><Picture item={b} className="h-24 w-32 shrink-0 rounded-md" /><div className="min-w-0">{b.kategori && <p className="text-xs font-bold" style={{ color: b.kategori.warna }}>{b.kategori.nama}</p>}<h3 className="mt-1 line-clamp-2 font-bold leading-snug text-charcoal group-hover:text-primary" style={{ fontFamily: 'var(--font-heading)' }}>{b.judul}</h3><p className="mt-2 text-xs text-text-muted">{date(b.published_at)}</p></div></Link>)}</div></section>}
            <h2 className="mb-5 border-b border-charcoal pb-3 text-xl font-extrabold text-charcoal" style={{ fontFamily: 'var(--font-heading)' }}>Berita Terbaru</h2><section className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.slice(data.length > 3 ? 4 : 0).map((b) => <Link key={b.id} href={`/berita/${b.slug}`} className="group overflow-hidden rounded-lg bg-white shadow-subtle"><Picture item={b} className="h-44" /><div className="p-5">{b.kategori && <Badge color={b.kategori.warna} className="mb-2">{b.kategori.nama}</Badge>}<h3 className="line-clamp-2 font-extrabold leading-snug text-charcoal group-hover:text-primary" style={{ fontFamily: 'var(--font-heading)' }}>{b.judul}</h3><p className="mt-2 line-clamp-2 text-sm text-text-secondary">{b.ringkasan}</p><p className="mt-3 text-xs text-text-muted">{date(b.published_at)}</p></div></Link>)}</section>
        </div></main>
    </PublicLayout>;
}
